apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: godepviz
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: github.com/google/go-containerregistry/cmd/godepviz
