apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: explore
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/google/go-containerregistry/cmd/explore
            env:
            - name: TARGET
              value: "Go Sample v1"
